name: Go

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches:
            - main
            - release**

jobs:

  build:
    if: github.event.pull_request.draft == false
    name: Build and test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3.1.0
      with:
        version: latest

    - name: Test
      run: go test -v -race ./...
